// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function AddPeer(req: models$0.AddPeerRequest): $CancellablePromise<models$0.AddPeerResult> {
    return $Call.ByID(2148112281, req);
}

export function CreateInterface(req: models$0.CreateInterfaceRequest): $CancellablePromise<models$0.WGInterface> {
    return $Call.ByID(988100633, req);
}

export function DeleteInterface(serverID: string, name: string): $CancellablePromise<boolean> {
    return $Call.ByID(3786164332, serverID, name);
}

export function GenerateKeyPair(serverID: string): $CancellablePromise<models$0.KeyPair> {
    return $Call.ByID(2202449268, serverID);
}

export function GetInterfaceConfig(serverID: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1337927723, serverID, name);
}

export function GetStatus(serverID: string): $CancellablePromise<models$0.WGStatus> {
    return $Call.ByID(552800524, serverID);
}

export function RemovePeer(serverID: string, iface: string, publicKey: string): $CancellablePromise<boolean> {
    return $Call.ByID(312014626, serverID, iface, publicKey);
}

export function SyncConfig(serverID: string, name: string): $CancellablePromise<boolean> {
    return $Call.ByID(613508359, serverID, name);
}
