// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    AddPeerRequest,
    AddPeerResult,
    CreateInterfaceRequest,
    KeyPair,
    ServerConfig,
    TestConnectionResult,
    UpdatePeerMetaRequest,
    WGInterface,
    WGPeer,
    WGStatus
} from "./models.js";
