// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../ssh/models.js";

/**
 * @param {models$0.ServerConfig} server
 * @returns {$CancellablePromise<models$0.ServerConfig>}
 */
export function AddServer(server) {
    return $Call.ByID(3896640669, server).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function ClearLocalSessionCredentials() {
    return $Call.ByID(1031904017);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseAll() {
    return $Call.ByID(2684578068);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function DeleteServer(id) {
    return $Call.ByID(2028038223, id);
}

/**
 * @param {string} serverID
 * @returns {$CancellablePromise<ssh$0.Executor>}
 */
export function GetClient(serverID) {
    return $Call.ByID(1502784386, serverID);
}

/**
 * @returns {$CancellablePromise<models$0.LocalConfig>}
 */
export function GetLocalConfig() {
    return $Call.ByID(383668778).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.ServerConfig[]>}
 */
export function GetServers() {
    return $Call.ByID(247613383).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {models$0.LocalConfig} cfg
 * @returns {$CancellablePromise<boolean>}
 */
export function SaveLocalConfig(cfg) {
    return $Call.ByID(771587187, cfg);
}

/**
 * @param {string} username
 * @param {string} password
 * @returns {$CancellablePromise<boolean>}
 */
export function SetLocalSessionCredentials(username, password) {
    return $Call.ByID(1754628818, username, password);
}

/**
 * @param {models$0.ServerConfig} server
 * @returns {$CancellablePromise<models$0.TestConnectionResult>}
 */
export function TestConnection(server) {
    return $Call.ByID(1238645035, server).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {models$0.ServerConfig} server
 * @returns {$CancellablePromise<models$0.ServerConfig>}
 */
export function UpdateServer(server) {
    return $Call.ByID(2251486649, server).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.ServerConfig.createFrom;
const $$createType1 = models$0.LocalConfig.createFrom;
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = models$0.TestConnectionResult.createFrom;
