// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AddPeerRequest {
    "serverId": string;
    "interface": string;
    "publicKey": string;
    "allowedIPs": string[] | null;
    "presharedKey"?: string;
    "endpoint"?: string;
    "persistentKeepalive"?: number;
    "name"?: string;
    "description"?: string;
}

export interface AddPeerResult {
    "publicKey": string;
    "config": string;
}

export interface CreateInterfaceRequest {
    "serverId": string;
    "name": string;
    "listenPort": number;
    "privateKey"?: string;
    "endpoint"?: string;
    "allowedIPs"?: string[] | null;
    "address"?: string;
}

export interface KeyPair {
    "publicKey": string;
    "privateKey": string;
}

export interface LocalConfig {
    "username": string;
    "password"?: string;
    "configured": boolean;
}

export interface ServerConfig {
    "id": string;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "authMethod": string;
    "password"?: string;
    "privateKey"?: string;
    "passphrase"?: string;
    "viaServerId"?: string;
    "isLocal"?: boolean;
}

export interface TestConnectionResult {
    "success": boolean;
    "message": string;
}

export interface UpdatePeerMetaRequest {
    "serverId": string;
    "interface": string;
    "publicKey": string;
    "name"?: string;
    "description"?: string;
    "endpoint"?: string;
    "allowedIPs"?: string[] | null;
    "restart"?: boolean;
}

export interface WGInterface {
    "name": string;
    "publicKey": string;
    "privateKey"?: string;
    "listenPort": number;
    "endpoint"?: string;
    "rxBytes": number;
    "txBytes": number;
    "peers": WGPeer[] | null;
    "online": boolean;
}

export interface WGPeer {
    "publicKey": string;
    "presharedKey"?: string;
    "endpoint"?: string;
    "allowedIPs": string[] | null;
    "latestHandshake": string;
    "rxBytes": number;
    "txBytes": number;
    "persistentKeepalive"?: number;
    "name"?: string;
    "description"?: string;
}

export interface WGStatus {
    "interfaces": WGInterface[] | null;
    "hostname"?: string;
    "serverIP"?: string;
    "os"?: string;
    "packageManager"?: string;
    "wgNotInstalled"?: boolean;
}
