// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AddPeerRequest {
    /**
     * Creates a new AddPeerRequest instance.
     * @param {Partial<AddPeerRequest>} [$$source = {}] - The source object to create the AddPeerRequest.
     */
    constructor($$source = {}) {
        if (!("serverId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverId"] = "";
        }
        if (!("interface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interface"] = "";
        }
        if (!("publicKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publicKey"] = "";
        }
        if (!("allowedIPs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["allowedIPs"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["presharedKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["persistentKeepalive"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddPeerRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AddPeerRequest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedIPs" in $$parsedSource) {
            $$parsedSource["allowedIPs"] = $$createField3_0($$parsedSource["allowedIPs"]);
        }
        return new AddPeerRequest(/** @type {Partial<AddPeerRequest>} */($$parsedSource));
    }
}

export class AddPeerResult {
    /**
     * Creates a new AddPeerResult instance.
     * @param {Partial<AddPeerResult>} [$$source = {}] - The source object to create the AddPeerResult.
     */
    constructor($$source = {}) {
        if (!("publicKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publicKey"] = "";
        }
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["config"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddPeerResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AddPeerResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AddPeerResult(/** @type {Partial<AddPeerResult>} */($$parsedSource));
    }
}

export class CreateInterfaceRequest {
    /**
     * Creates a new CreateInterfaceRequest instance.
     * @param {Partial<CreateInterfaceRequest>} [$$source = {}] - The source object to create the CreateInterfaceRequest.
     */
    constructor($$source = {}) {
        if (!("serverId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("listenPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["listenPort"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["privateKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["allowedIPs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["address"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["enableService"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateInterfaceRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateInterfaceRequest}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedIPs" in $$parsedSource) {
            $$parsedSource["allowedIPs"] = $$createField5_0($$parsedSource["allowedIPs"]);
        }
        return new CreateInterfaceRequest(/** @type {Partial<CreateInterfaceRequest>} */($$parsedSource));
    }
}

export class KeyPair {
    /**
     * Creates a new KeyPair instance.
     * @param {Partial<KeyPair>} [$$source = {}] - The source object to create the KeyPair.
     */
    constructor($$source = {}) {
        if (!("publicKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publicKey"] = "";
        }
        if (!("privateKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["privateKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyPair instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeyPair}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyPair(/** @type {Partial<KeyPair>} */($$parsedSource));
    }
}

export class LocalConfig {
    /**
     * Creates a new LocalConfig instance.
     * @param {Partial<LocalConfig>} [$$source = {}] - The source object to create the LocalConfig.
     */
    constructor($$source = {}) {
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalConfig(/** @type {Partial<LocalConfig>} */($$parsedSource));
    }
}

export class ServerConfig {
    /**
     * Creates a new ServerConfig instance.
     * @param {Partial<ServerConfig>} [$$source = {}] - The source object to create the ServerConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("authMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authMethod"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["privateKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["passphrase"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["viaServerId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["isLocal"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerConfig(/** @type {Partial<ServerConfig>} */($$parsedSource));
    }
}

export class TestConnectionResult {
    /**
     * Creates a new TestConnectionResult instance.
     * @param {Partial<TestConnectionResult>} [$$source = {}] - The source object to create the TestConnectionResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestConnectionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestConnectionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestConnectionResult(/** @type {Partial<TestConnectionResult>} */($$parsedSource));
    }
}

export class UpdatePeerMetaRequest {
    /**
     * Creates a new UpdatePeerMetaRequest instance.
     * @param {Partial<UpdatePeerMetaRequest>} [$$source = {}] - The source object to create the UpdatePeerMetaRequest.
     */
    constructor($$source = {}) {
        if (!("serverId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverId"] = "";
        }
        if (!("interface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interface"] = "";
        }
        if (!("publicKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publicKey"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["newPublicKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["allowedIPs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["restart"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdatePeerMetaRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdatePeerMetaRequest}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedIPs" in $$parsedSource) {
            $$parsedSource["allowedIPs"] = $$createField7_0($$parsedSource["allowedIPs"]);
        }
        return new UpdatePeerMetaRequest(/** @type {Partial<UpdatePeerMetaRequest>} */($$parsedSource));
    }
}

export class WGInterface {
    /**
     * Creates a new WGInterface instance.
     * @param {Partial<WGInterface>} [$$source = {}] - The source object to create the WGInterface.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("publicKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publicKey"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["privateKey"] = undefined;
        }
        if (!("listenPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["listenPort"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (!("rxBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rxBytes"] = 0;
        }
        if (!("txBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["txBytes"] = 0;
        }
        if (!("peers" in $$source)) {
            /**
             * @member
             * @type {WGPeer[]}
             */
            this["peers"] = [];
        }
        if (!("online" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["online"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["serviceEnabled"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WGInterface instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WGInterface}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("peers" in $$parsedSource) {
            $$parsedSource["peers"] = $$createField7_0($$parsedSource["peers"]);
        }
        return new WGInterface(/** @type {Partial<WGInterface>} */($$parsedSource));
    }
}

export class WGPeer {
    /**
     * Creates a new WGPeer instance.
     * @param {Partial<WGPeer>} [$$source = {}] - The source object to create the WGPeer.
     */
    constructor($$source = {}) {
        if (!("publicKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publicKey"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["presharedKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (!("allowedIPs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["allowedIPs"] = [];
        }
        if (!("latestHandshake" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestHandshake"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("rxBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rxBytes"] = 0;
        }
        if (!("txBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["txBytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["persistentKeepalive"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WGPeer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WGPeer}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedIPs" in $$parsedSource) {
            $$parsedSource["allowedIPs"] = $$createField3_0($$parsedSource["allowedIPs"]);
        }
        return new WGPeer(/** @type {Partial<WGPeer>} */($$parsedSource));
    }
}

export class WGStatus {
    /**
     * Creates a new WGStatus instance.
     * @param {Partial<WGStatus>} [$$source = {}] - The source object to create the WGStatus.
     */
    constructor($$source = {}) {
        if (!("interfaces" in $$source)) {
            /**
             * @member
             * @type {WGInterface[]}
             */
            this["interfaces"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostname"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serverIP"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["os"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["packageManager"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["wgNotInstalled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["hasSystemd"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WGStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WGStatus}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("interfaces" in $$parsedSource) {
            $$parsedSource["interfaces"] = $$createField0_0($$parsedSource["interfaces"]);
        }
        return new WGStatus(/** @type {Partial<WGStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = WGPeer.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = WGInterface.createFrom;
const $$createType4 = $Create.Array($$createType3);
