// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Executor is the interface that both SSH and local clients implement.
 * wireguard.Service uses this abstraction to run commands on either
 * a remote server (via SSH) or the local machine (via os/exec).
 */
export type Executor = any;
