// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function AddPeer(req: models$0.AddPeerRequest): $CancellablePromise<models$0.AddPeerResult> {
    return $Call.ByID(3098433953, req);
}

export function BringDownInterface(serverID: string, name: string): $CancellablePromise<boolean> {
    return $Call.ByID(270780413, serverID, name);
}

export function BringUpInterface(serverID: string, name: string): $CancellablePromise<boolean> {
    return $Call.ByID(3850547026, serverID, name);
}

export function CancelInstall(): $CancellablePromise<boolean> {
    return $Call.ByID(3154375407);
}

export function CreateInterface(req: models$0.CreateInterfaceRequest): $CancellablePromise<models$0.WGInterface> {
    return $Call.ByID(441999553, req);
}

export function DeleteInterface(serverID: string, name: string): $CancellablePromise<boolean> {
    return $Call.ByID(1702654596, serverID, name);
}

/**
 * DisableService disables the wg-quick@<name> systemd unit so the interface
 * no longer auto-starts on boot. This does not change the current run state
 * of the interface.
 */
export function DisableService(serverID: string, name: string): $CancellablePromise<boolean> {
    return $Call.ByID(3984528589, serverID, name);
}

/**
 * EnableService enables the wg-quick@<name> systemd unit so the interface
 * auto-starts on boot. If the interface is currently up via wg-quick, it is
 * transitioned to systemd management atomically in a single command
 * (wg-quick down && systemctl enable --now) to avoid leaving the interface
 * down with the service not started.
 */
export function EnableService(serverID: string, name: string): $CancellablePromise<boolean> {
    return $Call.ByID(3086638492, serverID, name);
}

export function GenerateKeyPair(serverID: string): $CancellablePromise<models$0.KeyPair> {
    return $Call.ByID(1447813084, serverID);
}

export function GetInterfaceConfig(serverID: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3101484819, serverID, name);
}

export function GetStatus(serverID: string): $CancellablePromise<models$0.WGStatus> {
    return $Call.ByID(1337592116, serverID);
}

export function InstallWireGuard(serverID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2229465805, serverID);
}

export function RemovePeer(serverID: string, iface: string, publicKey: string): $CancellablePromise<boolean> {
    return $Call.ByID(1985494234, serverID, iface, publicKey);
}

export function RestartInterface(serverID: string, name: string): $CancellablePromise<boolean> {
    return $Call.ByID(2584832716, serverID, name);
}

export function SyncConfig(serverID: string, name: string): $CancellablePromise<boolean> {
    return $Call.ByID(1268158863, serverID, name);
}

export function UpdatePeerMeta(req: models$0.UpdatePeerMetaRequest): $CancellablePromise<boolean> {
    return $Call.ByID(1470998058, req);
}
