// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * @param {models$0.AddPeerRequest} req
 * @returns {$CancellablePromise<models$0.AddPeerResult>}
 */
export function AddPeer(req) {
    return $Call.ByID(3098433953, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} serverID
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function BringDownInterface(serverID, name) {
    return $Call.ByID(270780413, serverID, name);
}

/**
 * @param {string} serverID
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function BringUpInterface(serverID, name) {
    return $Call.ByID(3850547026, serverID, name);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function CancelInstall() {
    return $Call.ByID(3154375407);
}

/**
 * @param {models$0.CreateInterfaceRequest} req
 * @returns {$CancellablePromise<models$0.WGInterface>}
 */
export function CreateInterface(req) {
    return $Call.ByID(441999553, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} serverID
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function DeleteInterface(serverID, name) {
    return $Call.ByID(1702654596, serverID, name);
}

/**
 * DisableService disables the wg-quick@<name> systemd unit so the interface
 * no longer auto-starts on boot. This does not change the current run state
 * of the interface.
 * @param {string} serverID
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function DisableService(serverID, name) {
    return $Call.ByID(3984528589, serverID, name);
}

/**
 * EnableService enables the wg-quick@<name> systemd unit so the interface
 * auto-starts on boot. If the interface is currently up via wg-quick, it is
 * transitioned to systemd management atomically in a single command
 * (wg-quick down && systemctl enable --now) to avoid leaving the interface
 * down with the service not started.
 * @param {string} serverID
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function EnableService(serverID, name) {
    return $Call.ByID(3086638492, serverID, name);
}

/**
 * @param {string} serverID
 * @returns {$CancellablePromise<models$0.KeyPair>}
 */
export function GenerateKeyPair(serverID) {
    return $Call.ByID(1447813084, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} serverID
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetInterfaceConfig(serverID, name) {
    return $Call.ByID(3101484819, serverID, name);
}

/**
 * @param {string} serverID
 * @returns {$CancellablePromise<models$0.WGStatus>}
 */
export function GetStatus(serverID) {
    return $Call.ByID(1337592116, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} serverID
 * @returns {$CancellablePromise<boolean>}
 */
export function InstallWireGuard(serverID) {
    return $Call.ByID(2229465805, serverID);
}

/**
 * @param {string} serverID
 * @param {string} iface
 * @param {string} publicKey
 * @returns {$CancellablePromise<boolean>}
 */
export function RemovePeer(serverID, iface, publicKey) {
    return $Call.ByID(1985494234, serverID, iface, publicKey);
}

/**
 * @param {string} serverID
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function RestartInterface(serverID, name) {
    return $Call.ByID(2584832716, serverID, name);
}

/**
 * @param {string} serverID
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function SyncConfig(serverID, name) {
    return $Call.ByID(1268158863, serverID, name);
}

/**
 * @param {models$0.UpdatePeerMetaRequest} req
 * @returns {$CancellablePromise<boolean>}
 */
export function UpdatePeerMeta(req) {
    return $Call.ByID(1470998058, req);
}

// Private type creation functions
const $$createType0 = models$0.AddPeerResult.createFrom;
const $$createType1 = models$0.WGInterface.createFrom;
const $$createType2 = models$0.KeyPair.createFrom;
const $$createType3 = models$0.WGStatus.createFrom;
